# # everforest dark hard
# [colors.primary]
# background  =  "#272e33"
# foreground  =  "#d3c6aa"
#
# [colors.normal]
# black    =  "#414b50"
# red      =  "#e67e80"
# green    =  "#a7c080"
# yellow   =  "#dbbc7f"
# blue     =  "#7fbbb3"
# magenta  =  "#d699b6"
# cyan     =  "#83c092"
# white    =  "#d3c6aa"
#
# [colors.bright]
# black    =  "#475258"
# red      =  "#e67e80"
# green    =  "#a7c080"
# yellow   =  "#dbbc7f"
# blue     =  "#7fbbb3"
# magenta  =  "#d699b6"
# cyan     =  "#83c092"
# white    =  "#d3c6aa"

# # everforest dark medium
# [colors.primary]
# background  =  "#2d353b"
# foreground  =  "#d3c6aa"
#
# [colors.normal]
# black    =  "#475258"
# red      =  "#e67e80"
# green    =  "#a7c080"
# yellow   =  "#dbbc7f"
# blue     =  "#7fbbb3"
# magenta  =  "#d699b6"
# cyan     =  "#83c092"
# white    =  "#d3c6aa"
#
# [colors.bright]
# black    =  "#475258"
# red      =  "#e67e80"
# green    =  "#a7c080"
# yellow   =  "#dbbc7f"
# blue     =  "#7fbbb3"
# magenta  =  "#d699b6"
# cyan     =  "#83c092"
# white    =  "#d3c6aa"

# everforest dark soft
[colors.primary]
background  =  "#333c43"
foreground  =  "#d3c6aa"

[colors.normal]
black    =  "#4d5960"
red      =  "#e67e80"
green    =  "#a7c080"
yellow   =  "#dbbc7f"
blue     =  "#7fbbb3"
magenta  =  "#d699b6"
cyan     =  "#83c092"
white    =  "#d3c6aa"

[colors.bright]
black    =  "#4d5960"
red      =  "#e67e80"
green    =  "#a7c080"
yellow   =  "#dbbc7f"
blue     =  "#7fbbb3"
magenta  =  "#d699b6"
cyan     =  "#83c092"
white    =  "#d3c6aa"

# # everforest light hard
# [colors.primary]
# background  =  "#fffbef"
# foreground  =  "#5c6a72"
#
# [colors.normal]
# black    =  "#5c6a72"
# red      =  "#f85552"
# green    =  "#8da101"
# yellow   =  "#dfa000"
# blue     =  "#3a94c5"
# magenta  =  "#df69ba"
# cyan     =  "#35a77c"
# white    =  "#e8e5d5"
#
# [colors.bright]
# black    =  "#5c6a72"
# red      =  "#f85552"
# green    =  "#8da101"
# yellow   =  "#dfa000"
# blue     =  "#3a94c5"
# magenta  =  "#df69ba"
# cyan     =  "#35a77c"
# white    =  "#e8e5d5"

# # everforest light medium
# [colors.primary]
# background  =  "#fdf6e3"
# foreground  =  "#5c6a72"
#
# [colors.normal]
# black    =  "#5c6a72"
# red      =  "#f85552"
# green    =  "#8da101"
# yellow   =  "#dfa000"
# blue     =  "#3a94c5"
# magenta  =  "#df69ba"
# cyan     =  "#35a77c"
# white    =  "#e0dcc7"
#
# [colors.bright]
# black    =  "#5c6a72"
# red      =  "#f85552"
# green    =  "#8da101"
# yellow   =  "#dfa000"
# blue     =  "#3a94c5"
# magenta  =  "#df69ba"
# cyan     =  "#35a77c"
# white    =  "#e0dcc7"

# # everforest light soft
# [colors.primary]
# background  =  "#f3ead3"
# foreground  =  "#5c6a72"
#
# [colors.normal]
# black    =  "#5c6a72"
# red      =  "#f85552"
# green    =  "#8da101"
# yellow   =  "#dfa000"
# blue     =  "#3a94c5"
# magenta  =  "#df69ba"
# cyan     =  "#35a77c"
# white    =  "#d8d3ba"
#
# [colors.bright]
# black    =  "#5c6a72"
# red      =  "#f85552"
# green    =  "#8da101"
# yellow   =  "#dfa000"
# blue     =  "#3a94c5"
# magenta  =  "#df69ba"
# cyan     =  "#35a77c"
# white    =  "#d8d3ba"
