bindkey  -s  '^[[27;2;13~'  '\n'  #  <S-CR>  ->  <CR>
bindkey  -s  '^[OP'         ''    #  <F1>    ->  nothing
bindkey  -s  '^[OQ'         ''    #  <F2>    ->  nothing
bindkey  -s  '^[OR'         ''    #  <F3>    ->  nothing
bindkey  -s  '^[OS'         ''    #  <F4>    ->  nothing
bindkey  -s  '^[[15~'       ''    #  <F5>    ->  nothing
bindkey  -s  '^[[17~'       ''    #  <F6>    ->  nothing
bindkey  -s  '^[[18~'       ''    #  <F7>    ->  nothing
bindkey  -s  '^[[19~'       ''    #  <F8>    ->  nothing
bindkey  -s  '^[[20~'       ''    #  <F9>    ->  nothing
bindkey  -s  '^[[21~'       ''    #  <F10>   ->  nothing
bindkey  -s  '^[[24~'       ''    #  <F12>   ->  nothing
