return {
  {
    "L3MON4D3/LuaSnip",
    lazy = false,
    dependencies = {
      "rafamadriz/friendly-snippets",
      "hrsh7th/nvim-cmp",
      "hrsh7th/cmp-nvim-lsp",
      "saadparwaiz1/cmp_luasnip",
    },
    build = "make install_jsregexp",
    config = function()
      local ls = require("luasnip")
      local i = ls.insert_node
      local s = ls.snippet
      local t = ls.text_node
      ls.add_snippets("tex", {
        s("hw", {
          t({
            "\\documentclass[10pt]{article}",
            "",
            "\\usepackage{algorithm}",
            "\\usepackage[noend]{algpseudocode}",
            "\\usepackage{amsfonts}",
            "\\usepackage{amsmath}",
            "\\usepackage{amsthm}",
            "\\usepackage[style=numeric]{biblatex}",
            "\\usepackage{blkarray}",
            "\\usepackage{caption}",
            "\\usepackage{enumerate}",
            "\\usepackage{float}",
            "\\usepackage[top=1cm,bottom=2cm,left=1cm,right=1.75cm,marginparwidth=1.75cm]{geometry}",
            "\\usepackage[colorlinks=true,urlcolor=blue,citecolor=black]{hyperref}",
            "\\usepackage{mathtools}",
            "\\usepackage{tikz}",
            "",
            "\\def\\lp{\\left(}",
            "\\def\\rp{\\right)}",
            "\\def\\lf{\\left\\lfloor}",
            "\\def\\rf{\\right\\rfloor}",
            "\\def\\lc{\\left\\lceil}",
            "\\def\\rc{\\right\\rceil}",
            "\\def\\eps{\\varepsilon}",
            "\\def\\C{\\mathbb{C}}",
            "\\def\\I{\\mathbb{I}}",
            "\\def\\N{\\mathbb{N}}",
            "\\def\\R{\\mathbb{R}}",
            "\\def\\true{\\mathtt{TRUE}}",
            "\\def\\false{\\mathtt{FALSE}}",
            "\\def\\n{\\vspace{0.3cm}}",
            "",
            "\\newtheorem{theorem}{Theorem}",
            "\\newtheorem{lemma}[theorem]{Lemma}",
            "\\newcommand\\itm[1]{\\item[\\textbf{#1}]}",
            "",
            "\\setlength{\\parindent}{0cm}",
            "\\author{Fletcher Gornick}",
            "",
          }),
          t({ "\\title{\\vspace{-1.0cm}" }),
          i(1, "[[TITLE]]"),
          t({
            "}",
            "",
            "\\begin{document}",
            "\\maketitle",
            "\\begin{enumerate}",
            "\\itm{1.} ",
          }),
          i(2, ""),
          t({
            "",
            "\\end{enumerate}",
            "\\end{document}",
          }),
        }),
      })
    end,
  },
}
