require("config.alpha")
require("config.autopairs")
require("config.bufferline")
require("config.colors")
require("config.comment")
require("config.gitsigns")
require("config.hop")
require("config.markdown")
require("config.nvim-tree")
require("config.projects")
require("config.telescope")
require("config.treesitter")
require("config.vimtex")
require("config.wkey")

require("config.lsp.servers")
require("config.lsp.cmp")
require("config.lsp.fmt")
