require("nvim-autopairs").setup()
require("bufferline").setup()
require("nvim_comment").setup()
require("hop").setup()

require("config.alpha")
require("config.colors")
require("config.gitsigns")
require("config.projects")
require("config.telescope")
require("config.treesitter")
require("config.vimtex")
require("config.vstask")
require("config.which-key")

require("config.lsp.cmp")
require("config.lsp.debuggers")
require("config.lsp.formatters")
require("config.lsp.servers")
require("config.lsp.snippets")
