vim.o.timeout = true
vim.o.timeoutlen = 300

require("which-key").register({
    ["/"] = "toggle comment",
    c = "close buffer",
    d = {
        name = "dap",
        c = "continue",
        b = "breakpoint",
        B = "conditional bp",
        e = "evaluate",
        i = "step into",
        l = "run last",
        L = "set log point",
        o = "step over",
        O = "step out",
        r = "open debug console",
        R = "restart debugger",
        u = "toggle dapui",
    },
    e = "file explorer",
    f = {
        name = "fuzzy",
        b = "file browser",
        c = "nvim config files",
        C = "color schemes",
        f = "find files",
        g = "live grep",
        h = "help tags",
        k = "keymaps",
        o = "old files",
        p = "projects",
    },
    l = {
        name = "lsp info",
        a = "code action",
        i = "current buffer LSPs",
        m = "mason info",
        n = "null-ls info",
        r = "rename var",
    },
    p = {
        name = "packer",
        s = "sync",
    },
    q = "quit",
    t = {
        name = "terminal",
        v = "vertical",
        h = "horizontal",
    },
    w = "write",
    y = "which_key_ignore",
}, { prefix = "<leader>" })
