return {
    "stevearc/conform.nvim",
    lazy = false,
    opts = {
        formatters_by_ft = {
            bash = { "shfmt" },
            c = { "clang_format" },
            cpp = { "clang_format" },
            css = { "prettierd" },
            go = { "gofmt", "goimports" },
            glsl = { "clang_format" },
            graphql = { "prettierd" },
            haskell = { "fourmolu" },
            html = { "prettierd" },
            javascript = { "prettierd" },
            javascriptreact = { "prettierd" },
            json = { "prettierd" },
            jsonc = { "prettierd" },
            tex = { "latexindent" },
            lua = { "stylua" },
            markdown = { "prettierd" },
            python = { "ruff_format" },
            sh = { "shfmt" },
            typescript = { "prettierd" },
            typescriptreact = { "prettierd" },
            yaml = { "prettierd" },
            zsh = { "shfmt" },
            ["_"] = { "trim_whitespace", "trim_newlines" },
        },
        format_on_save = {
            lsp_fallback = true,
            timeout_ms = 500,
        },
        log_level = vim.log.levels.WARN,
        notify_on_error = false,
        formatters = {
            clang_format = { prepend_args = { "--style=InheritParentConfig" } },
            latexindent = { prepend_args = { "-y=defaultIndent:' '" } },
            stylua = {
                prepend_args = {
                    "--column-width=200",
                    "--collapse-simple-statement=Always",
                    "--indent-type=Spaces",
                    "--quote-style=AutoPreferDouble",
                    "--sort-requires",
                },
            },
        },
    },
}
