return {
    "stevearc/oil.nvim",
    lazy = false,
    dependencies = { "nvim-tree/nvim-web-devicons" },
    keys = { { "<leader>e", "<cmd>Oil<cr>", desc = "parent dir", mode = { "n", "v" } } },
    opts = {
        default_file_explorer = true,
        skip_confirm_for_simple_edits = true,
        prompt_save_on_select_new_entry = true,
        cleanup_delay_ms = false,
        view_options = {
            show_hidden = true,
        },
        keymaps = {
            ["g?"] = { "actions.show_help", mode = "n" },
            ["<cr>"] = "actions.select",
            ["<c-v>"] = { "actions.select", opts = { vertical = true } },
            ["<c-s>"] = { "actions.select", opts = { horizontal = true } },
            ["<c-t>"] = { "actions.select", opts = { tab = true } },
            ["<c-p>"] = "actions.preview",
            ["<c-c>"] = { "actions.close", mode = "n" },
            ["q"] = { "actions.close", mode = "n" },
            ["<c-l>"] = "actions.refresh",
            ["-"] = { "actions.parent", mode = "n" },
            ["gs"] = { "actions.change_sort", mode = "n" },
            ["gx"] = "actions.open_external",
            ["g."] = { "actions.toggle_hidden", mode = "n" },
            ["H"] = "actions.toggle_hidden",
            ["g\\"] = { "actions.toggle_trash", mode = "n" },
        },
        use_default_keymaps = false,
    },
    config = function(_, opts) require("oil").setup(opts) end,
}
