[shell]
program = "/opt/homebrew/bin/tmux"
args    = [ "new-session", "-A", "-s", "alacritty" ]

[window]
startup_mode  = "Fullscreen"
option_as_alt = "Both"

[font]
normal      = { family = "Hurmit Nerd Font Propo", style = "Regular"     }
bold        = { family = "Hurmit Nerd Font Propo", style = "Bold"        }
italic      = { family = "Hurmit Nerd Font Propo", style = "Italic"      }
bold_italic = { family = "Hurmit Nerd Font Propo", style = "Bold Italic" }
size        = 12

# everforest theme
[colors]
[colors.primary]
background = '#333c43'
foreground = '#d3c6aa'

[colors.normal]
black   = '#4d5960'
red     = '#e67e80'
green   = '#a7c080'
yellow  = '#dbbc7f'
blue    = '#7fbbb3'
magenta = '#d699b6'
cyan    = '#83c092'
white   = '#d3c6aa'

[colors.bright]
black   = '#4d5960'
red     = '#e67e80'
green   = '#a7c080'
yellow  = '#dbbc7f'
blue    = '#7fbbb3'
magenta = '#d699b6'
cyan    = '#83c092'
white   = '#d3c6aa'
