require("settings")
require("keymap")
require("plugins")

require("config.alpha")
require("config.bufferline")
require("config.gitsigns")
require("config.hop")
require("config.markdown")
require("config.autopairs")
require("config.comment")
require("config.navic")
require("config.nvim-tree")
require("config.projects")
require("config.telescope")
require("config.colorscheme")
require("config.treesitter")
require("config.vimtex")
require("config.which-key")

require("config.lsp.cmp")
require("config.lsp.mason")
require("config.lsp.zero")

require("config.fmt.fmt")
require("config.dap.dap")
