vim.g.mapleader = " "
vim.g.maplocalleader = "\\"
vim.opt.autochdir = true
vim.opt.clipboard = "unnamedplus"
vim.opt.completeopt = { "fuzzy", "menuone", "noselect" }
vim.opt.expandtab = true
vim.opt.inccommand = "split"
vim.opt.laststatus = 3
vim.opt.mousescroll = { "ver:1", "hor:1" }
vim.opt.number = true
vim.opt.shiftwidth = 4
vim.opt.showcmd = false
vim.opt.showtabline = 0
vim.opt.signcolumn = "yes"
vim.opt.smartindent = true
vim.opt.softtabstop = 4
vim.opt.splitbelow = true
vim.opt.splitright = true
vim.opt.swapfile = false
vim.opt.tabstop = 4
vim.opt.termguicolors = true
vim.opt.title = true
vim.opt.undofile = true
vim.opt.wrap = false
vim.opt.writebackup = false
